//------------------------------------------------------------------------------
// <auto-generated>
//     Este c�digo fue generado por una herramienta.
//     Versi�n de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podr�an causar un comportamiento incorrecto y se perder�n si
//     se vuelve a generar el c�digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.PriceComparison.Infrastructure.Persistence.Mysql {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder gener� autom�ticamente esta clase
    // a trav�s de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuaci�n, vuelva a ejecutar ResGen
    // con la opci�n /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageProviderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageProviderResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en cach� utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.PriceComparison.Infrastructure.Persistence.Mysql.MessageProviderResource", typeof(MessageProviderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   b�squedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be greather than 0.
        /// </summary>
        public static string ErrorValidatorFieldGreatherThanZero {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldGreatherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be less than 12.
        /// </summary>
        public static string ErrorValidatorFieldLessThanTwelve {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldLessThanTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field cannot be empty.
        /// </summary>
        public static string ErrorValidatorFieldNotEmpty {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field cannot be null.
        /// </summary>
        public static string ErrorValidatorFieldNotNull {
            get {
                return ResourceManager.GetString("ErrorValidatorFieldNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The resolution type must be valid (FE or POS).
        /// </summary>
        public static string ErrorValidatorResolutionTypeValid {
            get {
                return ResourceManager.GetString("ErrorValidatorResolutionTypeValid", resourceCulture);
            }
        }

        public static string ErrorValidatorFieldPositive
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldPositive", resourceCulture);
            }
        }

        public static string ErrorValidatorFieldMustBeGreaterThanZero
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldMustBeGreaterThanZero", resourceCulture);
            }
        }

        public static string ErrorValidatorFieldMustBeNonNegative
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldMustBeNonNegative", resourceCulture);
            }
        }


        public static string ErrorValidatorFieldMustBePercentage
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldMustBePercentage", resourceCulture);
            }
        }

        public static string ErrorValidatorInvalidEmail
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorInvalidEmail", resourceCulture);
            }
        }

        public static string ErrorValidatorFieldIsRequired
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldIsRequired", resourceCulture);
            }
        }

        public static string ErrorValidatorFieldMustBeGreaterThanOrEqualToZero
        {
            get
            {
                return ResourceManager.GetString("ErrorValidatorFieldMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
    }

}
