// <auto-generated />
using Backend.PriceComparison.Infrastructure.Persistence.Mysql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.PriceComparison.Infrastructure.Persistence.Mysql.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260506131645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientLegalPosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ElectronicInvoiceEmail")
                        .HasColumnType("longtext");

                    b.Property<bool>("LargeTaxpayer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SelfRetainer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SimpleTaxRegime")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VATResponsibleParty")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("VerificationDigit")
                        .HasColumnType("int");

                    b.Property<bool>("WithholdingAgent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ClientLegalPos");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientNaturalPosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ElectronicInvoiceEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ClientNaturalPos");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fields")
                        .HasColumnType("longtext");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext");

                    b.Property<string>("HelpTextHeader")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regex")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientLegalPosEntity", b =>
                {
                    b.HasOne("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientNaturalPosEntity", b =>
                {
                    b.HasOne("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
