// <auto-generated />
using Backend.PriceComparison.Infrastructure.Persistence.Mysql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.PriceComparison.Infrastructure.Persistence.Mysql.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientLegalPosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ElectronicInvoiceEmail")
                        .HasColumnType("longtext");

                    b.Property<bool>("LargeTaxpayer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SelfRetainer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SimpleTaxRegime")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VATResponsibleParty")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("VerificationDigit")
                        .HasColumnType("int");

                    b.Property<bool>("WithholdingAgent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ClientLegalPos");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientNaturalPosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ElectronicInvoiceEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ClientNaturalPos");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fields")
                        .HasColumnType("longtext");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext");

                    b.Property<string>("HelpTextHeader")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regex")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentType = "CC",
                            HelpText = "Número de cédula sin puntos ni espacios",
                            HelpTextHeader = "Ingrese su cédula",
                            Name = "Cédula de Ciudadanía",
                            Regex = "^[0-9]{6,10}$"
                        },
                        new
                        {
                            Id = 2,
                            DocumentType = "CE",
                            HelpText = "Número de cédula de extranjería",
                            HelpTextHeader = "Ingrese su cédula de extranjería",
                            Name = "Cédula de Extranjería",
                            Regex = "^[0-9]{6,12}$"
                        },
                        new
                        {
                            Id = 3,
                            DocumentType = "NIT",
                            HelpText = "Número de Identificación Tributario sin dígito de verificación",
                            HelpTextHeader = "Ingrese el NIT",
                            Name = "NIT",
                            Regex = "^[0-9]{6,12}$"
                        },
                        new
                        {
                            Id = 4,
                            DocumentType = "PP",
                            HelpText = "Número de pasaporte",
                            HelpTextHeader = "Ingrese su pasaporte",
                            Name = "Pasaporte",
                            Regex = "^[A-Za-z0-9]{6,20}$"
                        },
                        new
                        {
                            Id = 5,
                            DocumentType = "RC",
                            HelpText = "Número de registro civil",
                            HelpTextHeader = "Ingrese el registro civil",
                            Name = "Registro Civil",
                            Regex = "^[0-9]{6,10}$"
                        });
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientLegalPosEntity", b =>
                {
                    b.HasOne("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Backend.PriceComparison.Domain.ClientPos.Entities.ClientNaturalPosEntity", b =>
                {
                    b.HasOne("Backend.PriceComparison.Domain.ClientPos.Entities.DocumentTypeEntity", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
